import { identity,serviceClient,sameOrigin } from '@/lib/supabase/server';
import { validateContent } from '@/lib/content-validation';
import { managedEntry } from '@/lib/managed-content';
import { processes } from '@/lib/processes';
import { capabilities } from '@/lib/capabilities';
import { machineTypes } from '@/lib/machines';
import { getR2Text } from '@/lib/r2';
export async function GET(request:Request){const user=await identity();if(!user?.admin)return new Response('Forbidden',{status:403});const key=new URL(request.url).searchParams.get('key')??'';if(!validateContent(key,{}))return new Response('Unknown entry',{status:404});try{const saved=await managedEntry(key);const [kind,id]=key.split(':');const process=processes.find(p=>p.slug===id);const capability=capabilities.find(c=>c.id===id);const type=machineTypes.find(m=>m.id===id);let data:Record<string,unknown>={};if(kind==='process'&&process){data={name:process.name,summary:process.summary,description:process.description,materials:process.materials,features:process.features,applications:process.applications,markdown:process.sourceKey?await getR2Text(process.sourceKey):`# ${process.name}\n\n### 1. Process Overview & Definition\n${process.description}\n\n### 3. Key Process Parameters\n${process.parameters?.map(p=>`* **${p.name}:** ${p.value} ${p.unit}`).join('\n')||'Not documented.'}`};}else if(kind==='capability'&&capability)data={name:capability.name,description:capability.description};else if(type)data={name:type.name,text:type.text};const {data:history}=await serviceClient().from('omkar_revisions').select('version,created_at,editor_id').eq('key',key).order('version',{ascending:false}).limit(20);return Response.json({key,data:{...data,...saved?.data},version:saved?.version??0,history:history??[]},{headers:{'Cache-Control':'private, no-store'}});}catch{return new Response('Unable to load content',{status:503});}}
export async function PUT(request:Request){const user=await identity();if(!user?.admin)return new Response('Forbidden',{status:403});if(!sameOrigin(request))return new Response('Forbidden',{status:403});if(Number(request.headers.get('content-length')??0)>300000)return new Response('Content too large',{status:413});try{const raw=await request.text();if(raw.length>300000)return new Response('Content too large',{status:413});const body=JSON.parse(raw);if(typeof body.key!=='string'||!Number.isInteger(body.version)||body.version<0||!validateContent(body.key,body.data))return Response.json({error:'Invalid content fields'},{status:400});const {data,error}=await serviceClient().rpc('omkar_publish',{p_key:body.key,p_data:body.data,p_version:body.version,p_editor:user.id});if(error)return Response.json({error:error.message.includes('Version conflict')?'Someone edited this entry. Reload before publishing.':'Unable to publish changes'},{status:error.message.includes('Version conflict')?409:503});return Response.json({version:data});}catch{return Response.json({error:'Invalid request'},{status:400});}}
