"use client";
import { useState } from 'react';
import Link from 'next/link';
import { browserAuth } from '@/lib/supabase/browser';
export function AuthForm({signup=false,admin=false}:{signup?:boolean;admin?:boolean}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{
  const client=browserAuth();
  if(signup){const {error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/confirm`}});if(error)throw error;setMessage('Check your email to confirm your account, then sign in. If you already have an account, use Sign in.');}
  else {const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;const res=await fetch('/api/session');const session=await res.json();if(!res.ok)throw new Error('Confirm your email before signing in.');if(admin&&!session.admin)throw new Error('This account does not have administrator access.');const next=new URLSearchParams(window.location.search).get('next');window.location.assign(admin?'/admin':next?.startsWith('/')&&!next.startsWith('//')&&!next.includes('\\')?next:'/');}
 }catch(e){setMessage(e instanceof Error?e.message:'Unable to sign in. Try again.');}finally{setBusy(false);}}
 async function emailLink(){if(!email){setMessage('Enter your email address first.');return;}setBusy(true);try{const {error}=await browserAuth().auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:`${window.location.origin}/auth/confirm`}});if(error)throw error;setMessage('If this address has an account, a sign-in link has been sent.');}catch{setMessage('Unable to send a link. Please try again later.');}finally{setBusy(false);}}
 return <main className="auth-page"><Link href="/login" className="auth-brand">OMKAR</Link><h1>{signup?'Create an account':admin?'Administrator sign in':'Sign in to OMKAR'}</h1><p>{admin?'Only designated administrators can publish edits and manage correction requests.':'An account is required to explore the libraries and report corrections.'}</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?12:undefined} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{signup&&<small>Use at least 12 characters. Confirm your email to activate your account.</small>}<button className="orange-button" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form>{!signup&&<button className="text-button" onClick={emailLink} disabled={busy}>Email me a sign-in link instead</button>}<p role="status">{message}</p><div className="auth-links"><Link href={signup?'/login':'/signup'}>{signup?'Already registered? Sign in':'Create an account'}</Link><Link href={admin?'/login':'/admin/login'}>{admin?'Member sign in':'Admin sign in'}</Link></div></main>;
}
