"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
type Report={id:string;page_path:string;message:string;status:string;admin_note:string};
export function MemberTools(){
 const [admin,setAdmin]=useState(false);const [open,setOpen]=useState(false);const [message,setMessage]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [reports,setReports]=useState<Report[]>([]);
 useEffect(()=>{fetch('/api/session').then(r=>r.json()).then(u=>setAdmin(!!u.admin)).catch(()=>{});},[]);
 async function load(){const res=await fetch('/api/reports');if(res.ok)setReports(await res.json());}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const res=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,page_path:window.location.pathname})});const body=await res.json();if(!res.ok)throw new Error(body.error);setStatus('Correction request submitted. An administrator can review it.');setMessage('');await load();}catch(e){setStatus(e instanceof Error?e.message:'Unable to submit request.');}finally{setBusy(false);}}
 return <><div className="member-tools">{admin&&<Link href="/admin">Admin dashboard</Link>}<button onClick={()=>{setOpen(true);void load();}}>Report an issue</button><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login');}}>Sign out</button></div>{open&&<div className="dialog-backdrop"><section className="dialog report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-heading"><button className="close-account" autoFocus onClick={()=>setOpen(false)} aria-label="Close report form">×</button><h2 id="report-heading">Report incorrect information</h2><p>This request will include the current page address.</p><form onSubmit={submit}><label>What should be corrected?<textarea required minLength={10} maxLength={5000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Describe the issue and include supporting evidence or a source link."/></label><button className="orange-button" disabled={busy}>{busy?'Submitting…':'Submit correction request'}</button></form><p role="status">{status}</p><h3>{admin?"Recent correction requests":"Your recent requests"}</h3>{reports.map(r=><article key={r.id}><p>{r.message}</p><small>{r.status} · {r.page_path}</small>{r.admin_note&&<p>Admin response: {r.admin_note}</p>}</article>)}</section></div>}</>;
}
