"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Boxes, Cog, Factory, Globe2, Layers3, Search, SlidersHorizontal, Wrench, X, Menu, ChevronRight, Gauge, Flame, CircuitBoard } from "lucide-react";
import { useCatalog, CatalogProvider } from "./catalog-provider";
import { MemberTools } from "./member-tools";
import { ManufacturingLibrary } from "./manufacturing-library";
import dynamic from "next/dynamic";
import { KnowledgeSearch } from "./knowledge-search";
import { CapabilityCatalog } from "./capability-catalog";


const ImportedProfile = dynamic(() => import("./imported-profile").then(m => m.ImportedProfile));

type Screen = "home" | "contribute" | "search" | "machines" | "processes" | "capabilities" | "requirements" | "detail" | "about";
const families = ["Subtractive Manufacturing", "Additive Manufacturing", "Forming", "Casting", "Joining", "Surface Engineering & Finishing", "Heat Treatment", "Hybrid Processes"];
const symbols = [Cog, Layers3, Wrench, Boxes, CircuitBoard, Gauge, Flame, Factory];
const nav = [["Home","/","home"],["Processes","/processes","processes"],["Capabilities","/capabilities","capabilities"],["Machines","/machines","machines"],["Knowledge Explorer","/search","search"],["Contribute","/contribute","contribute"],["About","/about","about"]];
function familyOf(family:string) { return family === "Formative Manufacturing" ? "Casting" : family; }

export function Portal(props:{screen:Screen;slug?:string}) {return <CatalogProvider><PortalContent {...props}/></CatalogProvider>;}
function PortalContent({screen,slug}: {screen:Screen;slug?:string}) {
 const {processes,machineTypes,machineModels}=useCatalog();
 const modelsForType=(id:string)=>machineModels.filter(m=>m.machineTypeId===id);
 const [query,setQuery] = useState("");
 const [family,setFamily] = useState("All processes");
 const [machineCategory,setMachineCategory] = useState("All machine types");
 const [menu,setMenu] = useState(false);
 const [filters,setFilters] = useState(true);
 const normalized=query.toLowerCase().trim();
 const matches=processes.filter(p => (family === "All processes" || familyOf(p.family) === family) && [p.name,p.family,p.summary,...p.features,...p.materials].join(" ").toLowerCase().includes(normalized));
 const visibleMachines=machineTypes.filter(m => (machineCategory === "All machine types" || m.category === machineCategory) && `${m.name} ${m.text}`.toLowerCase().includes(normalized));
 const detailProcess=processes.find(p=>p.slug===slug);
 const title=screen==="machines"?"Machine Library":"Process Library";
 return <div className="portal">
  <header className="portal-header"><Link href="/" className="portal-logo" aria-label="OMKAR home"><Image src="/omkar-logo.png" alt="OMKAR — Open Manufacturing Knowledge and Resources" width={626} height={232} priority/><span className="portal-logo-expansion" aria-hidden="true">Open Manufacturing Knowledge and Resources</span></Link><button className="portal-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu/></button><nav className={menu?"visible":""} aria-label="Main navigation">{nav.map(([name,href,id])=><Link key={id} href={href} aria-current={screen===id || (screen==="detail" && id==="processes")?"page":undefined}>{name}</Link>)}</nav><MemberTools/></header>
  {screen === "home" ? <>
   <section className="landing-hero"><div className="hero-kicker">KNOWLEDGE. CONNECTED. MANUFACTURING.</div><h1>Explore <em>manufacturing knowledge</em></h1><p>Processes • Capabilities • Machines • Materials</p><form action="/search" className="portal-search hero-search"><Search size={19}/><input name="q" aria-label="Search manufacturing knowledge" placeholder="Search OMKAR…"/><button className="orange-button">Search</button></form><div className="search-hints">Try: <Link href="/processes/milling">milling</Link><span>·</span><Link href="/processes/turning">turning</Link><span>·</span><Link href="/processes/broaching">internal profiles</Link></div><div className="entry-cards">{[{name:"Machine Types",href:"/machines",icon:Factory,text:"Browse machine types and their documented manufacturer models."},{name:"Manufacturing Processes",href:"/processes",icon:Cog,text:"Discover the principles and possibilities of manufacturing."},{name:"Capabilities",href:"/capabilities",icon:Boxes,text:"Explore the functions processes require and machines must provide."}].map((c,i)=><Link href={c.href} className={`entry-card entry-${i}`} key={c.name}><c.icon size={28}/><h2>{c.name}</h2><p>{c.text}</p><span>Explore {i===0?"Machines":i===1?"Processes":"Capabilities"}<ArrowRight size={16}/></span></Link>)}</div></section>
   <section className="portal-section"><div className="section-heading"><div><h2>Explore the Process Library</h2><p>A structured world of manufacturing, from fundamentals to advanced applications.</p></div><Link href="/processes">View all processes <ArrowRight size={15}/></Link></div><div className="family-grid">{families.map((f,i)=>{const Icon=symbols[i];const count=processes.filter(p=>familyOf(p.family)===f).length;return <Link href={`/processes?family=${encodeURIComponent(f)}`} key={f}><div className="family-art"><Icon/></div><h3>{f}</h3><span>{count?`${count} process${count>1?"es":""}`:"Collection coming soon"}<ArrowRight size={13}/></span></Link>;})}</div></section><Stats/>
  </> : screen === "detail" ? <div className="portal-detail"><div className="portal-breadcrumb"><Link href="/">Home</Link><ChevronRight size={12}/><Link href="/processes">Process Library</Link><ChevronRight size={12}/><span>{processes.find(p=>p.slug===slug)?.name}</span></div>{detailProcess?.sourceKey ? <ImportedProfile key={slug} process={detailProcess}/> : <ManufacturingLibrary key={slug} initialProcesses={processes} initialSlug={slug} embedded/>}</div>
  : screen === "contribute" ? <section className="about-screen portal-section"><span className="orange-label">BUILD SHARED KNOWLEDGE</span><h1>Contribute to OMKAR</h1><p>Help document manufacturing processes, functional capabilities, and machine models with traceable sources.</p><div className="about-grid"><article><BookOpen/><h2>Process knowledge</h2><p>Prepare a Markdown profile covering inputs, outputs, parameters, process steps, required capabilities, and references.</p></article><article><Factory/><h2>Machine models</h2><p>Include the manufacturer, model, configuration, specifications, capability limits, and supporting documentation.</p></article><article><Globe2/><h2>Evidence and diagrams</h2><p>Include source references and image credits, and identify assumptions or values that still need verification.</p></article></div><p>Use “Report an issue” on any page to submit a correction request with your evidence. Administrators can review requests and publish library edits directly.</p><Link className="orange-button" href="/processes/drilling">View an example profile <ArrowRight size={16}/></Link></section>
  : screen === "search" ? <KnowledgeSearch/>
  : screen === "about" ? <section className="about-screen portal-section"><span className="orange-label">A GLOBAL PLATFORM</span><h1>Manufacturing knowledge,<br/>open to possibility.</h1><p>OMKAR — Open Manufacturing Knowledge and Resources — brings machines, processes, and capabilities into one connected library.</p><div className="about-grid">{[{icon:BookOpen,title:"Understand the process",text:"Explore how materials become parts, from cutting and shaping to finished geometry."},{icon:Factory,title:"Explore the equipment",text:"Connect manufacturing machines with the processes they make possible."},{icon:Globe2,title:"Build shared knowledge",text:"A growing reference for engineers, students, and manufacturing professionals."}].map(c=><article key={c.title}><c.icon/><h2>{c.title}</h2><p>{c.text}</p></article>)}</div><Link className="orange-button" href="/processes">Explore the library <ArrowRight size={16}/></Link></section>
  : screen === "capabilities" || screen === "requirements" ? <CapabilityCatalog domain={screen}/>
  : <><section className={`catalog-hero ${screen}`}><span className="orange-label">EXPLORE OMKAR</span><h1>{title}</h1><p>{screen==="machines"?"Machine types describe equipment classes. Machine models identify manufacturer products and configurations, where specifications and capability limits are documented.":"Discover the principles, possibilities, and applications of manufacturing."}</p></section><section className="portal-section"><SearchFilters query={query} onQuery={setQuery} filters={filters} onFilters={()=>setFilters(!filters)} onInitialFamily={setFamily}/><div className={`catalog-layout ${!filters?"without-filter":""}`}>{filters&&<aside className="catalog-sidebar"><h3>{screen==="machines"?"Machine type categories":"Process families"}</h3>{(screen==="machines"?["All machine types","Machining","Thermal Cutting","Casting"]:["All processes",...families]).map(f=><button key={f} className={(screen==="machines"?machineCategory:family)===f?"selected":""} onClick={()=>screen==="machines"?setMachineCategory(f):setFamily(f)}>{f}<ChevronRight size={12}/></button>)}</aside>}<div><div className="results-label">{screen==="machines"?visibleMachines.length:matches.length} {screen==="machines"?"machine types":"processes"} available</div><div className="catalog-grid">{screen==="machines"?visibleMachines.map((m,i)=>{const Icon=symbols[i];return <article className="catalog-card" key={m.name}><div className="catalog-art"><Icon size={72}/><span>0{i+1}</span></div><div className="catalog-card-body"><small>Machine Type · {m.category}</small><h2>{m.name}</h2><p>{m.text}</p><div className="machine-models"><h3>Machine Models</h3>{modelsForType(m.id).length ? modelsForType(m.id).map(model=><details key={model.id}><summary>{model.manufacturer} {model.name}</summary><p>{model.configuration}</p><dl>{model.specifications.map(spec=><div key={spec.parameter}><dt>{spec.parameter}</dt><dd>{spec.value} {spec.unit}</dd></div>)}</dl></details>) : <p>No models documented yet. Specifications, settings, documentation, and offered capabilities will be recorded per model.</p>}</div><Link href={`/processes/${m.process}`}>Explore process <ArrowRight size={15}/></Link></div></article>;}):matches.map(p=><article className="catalog-card" key={p.slug}><Link href={`/processes/${p.slug}`} className={`catalog-art art-${p.slug}`} aria-label={`Explore ${p.name}`}>{p.images?.length ? <Image unoptimized src={`/api/media/${p.slug}/0`} alt={`${p.name} diagram`} fill sizes="(max-width:760px) 45vw, 25vw" style={{objectFit:"contain"}}/> : <><Cog size={72}/><span>{p.icon}</span></>}</Link><div className="catalog-card-body"><small>{familyOf(p.family)}</small><h2><Link href={`/processes/${p.slug}`}>{p.name}</Link></h2><p>{p.summary}</p><Link href={`/processes/${p.slug}`}>Explore process <ArrowRight size={15}/></Link></div></article>)}</div>{(screen==="machines"?visibleMachines.length:matches.length)===0&&<Empty/>}</div></div></section></>}
  <footer className="portal-footer"><Link href="/">OM<span>K</span>AR</Link><p>Open Manufacturing Knowledge and Resources</p><Link href="/requirements">Requirements / Outcomes</Link><span>Explore. Understand. Manufacture.</span></footer>

 </div>;
}

function SearchFilters({query,onQuery,filters,onFilters,onInitialFamily}:{query:string;onQuery:(s:string)=>void;filters:boolean;onFilters:()=>void;onInitialFamily:(s:string)=>void}) {
 // Read the optional URL filters after mounting so each page remains statically renderable.
 useEffect(() => {
  const params = new URLSearchParams(window.location.search);
  if (params.has("q")) onQuery(params.get("q")!);
  const f = params.get("family");
  if (f && families.includes(f)) onInitialFamily(f);
 }, [onQuery, onInitialFamily]);
 return <div className="catalog-tools"><label className="portal-search"><Search size={18}/><input aria-label="Search catalog" placeholder="Search processes, machines, materials…" value={query} onChange={e=>onQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>onQuery("")}><X size={16}/></button>}</label><button className="filter-button" aria-expanded={filters} onClick={onFilters}><SlidersHorizontal size={16}/>Filters</button></div>;
}
function Empty(){return <div className="catalog-empty"><Search size={32}/><h2>No entries available</h2><p>Try another search or category. More manufacturing collections will be added over time.</p></div>;}
function Stats(){const {processes,capabilities,machineTypes}=useCatalog();return <section className="portal-stats">{[{icon:BookOpen,n:String(processes.length),label:"Documented processes"},{icon:Factory,n:String(machineTypes.length),label:"Machine types"},{icon:Boxes,n:String(capabilities.length),label:"Functional capabilities"},{icon:Globe2,n:"Global",label:"Open knowledge for everyone"}].map(s=><div key={s.n+s.label}><s.icon/><span><b>{s.n}</b><small>{s.label}</small></span></div>)}<blockquote>“Manufacturing knowledge<br/>should be a global public good.”<small>— OMKAR</small></blockquote></section>;}
